using System.Collections.Specialized;
using System.ComponentModel;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Documents;
using Avalonia.Data;
using Avalonia.Layout;
using Avalonia.Markup.Xaml;
using Avalonia.Media;
using Base.It.App.ViewModels;
using Base.It.Core.Diff;

namespace Base.It.App.Views;

public partial class CompareTabView : UserControl
{
    private CompareTabViewModel? _vm;

    public CompareTabView()
    {
        // InitializeComponent (generated by the Avalonia name source generator)
        // loads the XAML AND assigns the named PanesHost field. AvaloniaXamlLoader.Load
        // alone does not populate generated fields.
        InitializeComponent();
        DataContextChanged += (_, _) => Bind();
        DetachedFromVisualTree += (_, _) => Unbind();
    }

    private void Bind()
    {
        Unbind();
        _vm = DataContext as CompareTabViewModel;
        if (_vm is null) return;
        _vm.Panes.CollectionChanged += OnPanesChanged;
        _vm.PropertyChanged         += OnVmPropertyChanged;
        Rebuild();
    }

    private void Unbind()
    {
        if (_vm is null) return;
        _vm.Panes.CollectionChanged -= OnPanesChanged;
        _vm.PropertyChanged         -= OnVmPropertyChanged;
        _vm = null;
    }

    private void OnPanesChanged(object? s, NotifyCollectionChangedEventArgs e) => Rebuild();
    private void OnVmPropertyChanged(object? s, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(CompareTabViewModel.ExpandedPane)) Rebuild();
    }

    private void Rebuild()
    {
        if (_vm is null || PanesHost is null) return;

        PanesHost.Children.Clear();
        PanesHost.ColumnDefinitions.Clear();

        var panes = _vm.ExpandedPane is { } exp ? new[] { exp } : _vm.Panes.ToArray();
        if (panes.Length == 0) return;

        for (int i = 0; i < panes.Length; i++)
        {
            PanesHost.ColumnDefinitions.Add(new ColumnDefinition(1, GridUnitType.Star) { MinWidth = 200 });
            if (i < panes.Length - 1)
                PanesHost.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Auto));
        }

        for (int i = 0; i < panes.Length; i++)
        {
            var paneControl = BuildPane(panes[i]);
            Grid.SetColumn(paneControl, i * 2);
            PanesHost.Children.Add(paneControl);

            if (i < panes.Length - 1)
            {
                var splitter = new GridSplitter
                {
                    Width = 6,
                    ResizeDirection = GridResizeDirection.Columns,
                    Background = Brushes.Transparent,
                    ShowsPreview = false,
                    VerticalAlignment = VerticalAlignment.Stretch
                };
                Grid.SetColumn(splitter, i * 2 + 1);
                PanesHost.Children.Add(splitter);
            }
        }
    }

    private Control BuildPane(EnvPane pane)
    {
        var header = BuildHeader(pane);

        var text = new SelectableTextBlock
        {
            FontFamily = new FontFamily("Cascadia Mono,Consolas,monospace"),
            FontSize = 12,
            TextWrapping = TextWrapping.NoWrap,
            Padding = new Thickness(10, 6),
            Background = Brushes.Transparent
        };
        PopulateInlines(text, pane.Lines);

        var scroll = new ScrollViewer
        {
            HorizontalScrollBarVisibility = Avalonia.Controls.Primitives.ScrollBarVisibility.Auto,
            VerticalScrollBarVisibility   = Avalonia.Controls.Primitives.ScrollBarVisibility.Auto,
            Content = text
        };
        scroll.Bind(ScrollViewer.OffsetProperty, new Binding(nameof(CompareTabViewModel.SharedScrollOffset))
        {
            Source = _vm,
            Mode = BindingMode.TwoWay
        });

        var outer = new Border
        {
            CornerRadius = new CornerRadius(6),
            BorderBrush = Application.Current!.TryGetResource(
                "ControlStrokeColorDefaultBrush", out var br) ? br as IBrush : Brushes.Gray,
            BorderThickness = new Thickness(1),
            ClipToBounds = true,
            Child = new Grid { RowDefinitions = new RowDefinitions("Auto,*") }
        };
        var grid = (Grid)outer.Child;
        Grid.SetRow(header, 0);
        Grid.SetRow(scroll, 1);
        grid.Children.Add(header);
        grid.Children.Add(scroll);
        return outer;
    }

    private Control BuildHeader(EnvPane pane)
    {
        var badge = new Border
        {
            CornerRadius = new CornerRadius(10),
            Padding = new Thickness(10, 3),
            VerticalAlignment = VerticalAlignment.Center,
            Background = (IBrush)ColorStringBrushConverter.Instance.Convert(
                pane.Color, typeof(IBrush), null, System.Globalization.CultureInfo.InvariantCulture)!,
            Child = new TextBlock
            {
                Text = pane.Label,
                Foreground = Brushes.White,
                FontSize = 11,
                FontWeight = FontWeight.SemiBold
            }
        };

        var changedCount = pane.Lines.Count(l => l.State == LineState.Different);
        var meta = new TextBlock
        {
            Text = changedCount == 0
                ? $"{pane.Lines.Count} lines, in sync"
                : $"{pane.Lines.Count} lines, {changedCount} differ",
            Opacity = 0.55, FontSize = 11,
            VerticalAlignment = VerticalAlignment.Center,
            Margin = new Thickness(10, 0, 0, 0)
        };

        var copyBtn = new Button
        {
            Content = "Copy",
            Padding = new Thickness(10, 4),
            Margin = new Thickness(6, 0, 0, 0),
            Command = _vm!.CopyAllCommand,
            CommandParameter = pane,
            [ToolTip.TipProperty] = "Copy the whole definition to the clipboard"
        };
        var expandBtn = new Button
        {
            Content = _vm.ExpandedPane is null ? "Expand" : "Restore",
            Padding = new Thickness(10, 4),
            Margin = new Thickness(6, 0, 0, 0),
            Command = _vm.ExpandedPane is null ? _vm.ExpandCommand : _vm.RestoreCommand,
            CommandParameter = pane,
            [ToolTip.TipProperty] = _vm.ExpandedPane is null ? "Show only this pane" : "Show all panes"
        };

        var right = new StackPanel
        {
            Orientation = Orientation.Horizontal,
            HorizontalAlignment = HorizontalAlignment.Right
        };
        right.Children.Add(copyBtn);
        right.Children.Add(expandBtn);

        var header = new Grid
        {
            ColumnDefinitions = new ColumnDefinitions("Auto,*,Auto"),
            Background = Application.Current!.TryGetResource(
                "LayerOnAcrylicFillColorDefaultBrush", out var bg) ? bg as IBrush : null,
        };
        Grid.SetColumn(badge, 0);
        Grid.SetColumn(meta,  1);
        Grid.SetColumn(right, 2);
        header.Children.Add(badge);
        header.Children.Add(meta);
        header.Children.Add(right);

        return new Border
        {
            Padding = new Thickness(10, 6),
            Child = header
        };
    }

    private static void PopulateInlines(SelectableTextBlock target, IReadOnlyList<AlignedPaneLine> lines)
    {
        target.Inlines?.Clear();
        if (target.Inlines is null) target.Inlines = new InlineCollection();

        IBrush? diffBg = Application.Current!.TryGetResource(
            "SystemFillColorCautionBackgroundBrush", out var r) ? r as IBrush : null;
        diffBg ??= new SolidColorBrush(Color.FromArgb(0x55, 0xFF, 0x80, 0x70));
        IBrush? diffFg = new SolidColorBrush(Color.FromArgb(0xFF, 0xFF, 0xB0, 0x90));

        for (int i = 0; i < lines.Count; i++)
        {
            var line = lines[i];
            var run = new Run(line.Text);
            if (line.State == LineState.Different)
            {
                run.Background = diffBg;
                run.Foreground = diffFg;
                run.FontWeight = FontWeight.SemiBold;
            }
            target.Inlines.Add(run);
            if (i < lines.Count - 1) target.Inlines.Add(new LineBreak());
        }
    }
}
