using System.Collections.Specialized;
using System.ComponentModel;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Documents;
using Avalonia.Data;
using Avalonia.Layout;
using Avalonia.Markup.Xaml;
using Avalonia.Media;
using Base.It.App.ViewModels;
using Base.It.Core.Diff;

namespace Base.It.App.Views;

public partial class CompareTabView : UserControl
{
    private CompareTabViewModel? _vm;

    /// <summary>Above this many lines the row-aligned renderer (one control
    /// per line × both sides) would spawn too many controls; fall back to the
    /// lighter flowing renderer.</summary>
    private const int AlignedMaxLines = 2000;

    public CompareTabView()
    {
        // InitializeComponent (generated by the Avalonia name source generator)
        // loads the XAML AND assigns the named PanesHost field. AvaloniaXamlLoader.Load
        // alone does not populate generated fields.
        InitializeComponent();
        DataContextChanged += (_, _) => Bind();
        DetachedFromVisualTree += (_, _) => Unbind();
    }

    /// <summary>Export this comparison (Line column + one per environment) to CSV.</summary>
    private async void OnExportCsvClick(object? sender, Avalonia.Interactivity.RoutedEventArgs e)
    {
        if (DataContext is not CompareTabViewModel vm) return;
        await Services.CsvExport.SaveAsync(this, vm, vm.Toasts);
    }

    private void Bind()
    {
        Unbind();
        _vm = DataContext as CompareTabViewModel;
        if (_vm is null) return;
        _vm.Panes.CollectionChanged += OnPanesChanged;
        _vm.PropertyChanged         += OnVmPropertyChanged;
        Rebuild();
    }

    private void Unbind()
    {
        if (_vm is null) return;
        _vm.Panes.CollectionChanged -= OnPanesChanged;
        _vm.PropertyChanged         -= OnVmPropertyChanged;
        _vm = null;
    }

    private void OnPanesChanged(object? s, NotifyCollectionChangedEventArgs e) => Rebuild();
    private void OnVmPropertyChanged(object? s, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(CompareTabViewModel.ExpandedPane)) Rebuild();
    }

    private void Rebuild()
    {
        if (_vm is null || PanesHost is null) return;

        PanesHost.Children.Clear();
        PanesHost.ColumnDefinitions.Clear();

        var panes = _vm.ExpandedPane is { } exp ? new[] { exp } : _vm.Panes.ToArray();
        if (panes.Length == 0) return;

        PanesHost.ColumnDefinitions.Add(new ColumnDefinition(1, GridUnitType.Star));

        // Two environments (not expanded) → git-style row-aligned side-by-side.
        // One (expanded) or 3+ → the N-pane AvaloniaEdit editor view (syntax
        // highlighting, find, scroll-sync) — the same robust editors as the
        // preview, instead of the old flowing text blocks.
        Control view =
            panes.Length == 2 && Math.Max(panes[0].Lines.Count, panes[1].Lines.Count) <= AlignedMaxLines
                ? BuildAlignedTwoPane(panes[0], panes[1])
                : BuildMultiPane(panes);
        Grid.SetColumn(view, 0);
        PanesHost.Children.Add(view);
    }

    /// <summary>N-pane (1 or 3+) view: per-pane [label + copy + expand] headers
    /// above the shared multi-editor body.</summary>
    private Control BuildMultiPane(EnvPane[] panes)
    {
        var isDark = Application.Current?.ActualThemeVariant == Avalonia.Styling.ThemeVariant.Dark;
        var built = SqlDiffEditor.BuildMulti(panes, isDark, _vm?.IgnoreWhitespace ?? false);
        var body = built.Body;

        var header = new Grid();
        for (int i = 0; i < panes.Length; i++)
        {
            header.ColumnDefinitions.Add(new ColumnDefinition(1, GridUnitType.Star));
            if (i < panes.Length - 1) header.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Auto));

            Control h = BuildHeader(panes[i]);
            // Per-target change navigator (each non-base column), like the 2-pane view.
            if (i < built.Panes.Count && !built.Panes[i].IsBase && built.Panes[i].Hunks.Count > 0)
            {
                var dock = new DockPanel { LastChildFill = true };
                var nav = SqlDiffEditor.BuildPaneNavigator(built.Panes[i]);
                DockPanel.SetDock(nav, Dock.Right);
                dock.Children.Add(nav);
                dock.Children.Add(h);
                h = dock;
            }
            Grid.SetColumn(h, i * 2);
            header.Children.Add(h);
        }

        var outer = new Border
        {
            CornerRadius = new CornerRadius(6),
            BorderBrush = Application.Current!.TryGetResource(
                "ControlStrokeColorDefaultBrush", out var br) ? br as IBrush : Brushes.Gray,
            BorderThickness = new Thickness(1),
            ClipToBounds = true,
            Child = new Grid { RowDefinitions = new RowDefinitions("Auto,*") },
        };
        var grid = (Grid)outer.Child;
        Grid.SetRow(header, 0);
        Grid.SetRow(body, 1);
        grid.Children.Add(header);
        grid.Children.Add(body);
        return outer;
    }

    /// <summary>
    /// Git-style 2-pane view: the two per-pane headers side by side above the
    /// shared row-aligned body from <see cref="AlignedDiffView"/> (which owns
    /// its own single scroll viewer, so no SharedScrollOffset sync is needed
    /// and there's no click-scroll-reset).
    /// </summary>
    private Control BuildAlignedTwoPane(EnvPane left, EnvPane right)
    {
        var header = new Grid { ColumnDefinitions = new ColumnDefinitions("*,*") };
        var lh = BuildHeader(left);
        var rh = BuildHeader(right);
        Grid.SetColumn(lh, 0);
        Grid.SetColumn(rh, 1);
        header.Children.Add(lh);
        header.Children.Add(rh);

        var isDark = Application.Current?.ActualThemeVariant == Avalonia.Styling.ThemeVariant.Dark;
        var built = SqlDiffEditor.Build(left, right, isDark);

        var outer = new Border
        {
            CornerRadius = new CornerRadius(6),
            BorderBrush = Application.Current!.TryGetResource(
                "ControlStrokeColorDefaultBrush", out var br) ? br as IBrush : Brushes.Gray,
            BorderThickness = new Thickness(1),
            ClipToBounds = true,
            Child = new Grid { RowDefinitions = new RowDefinitions("Auto,*") },
        };
        var grid = (Grid)outer.Child;
        Grid.SetRow(header, 0);
        Grid.SetRow(built.Body, 1);
        grid.Children.Add(header);
        grid.Children.Add(built.Body);
        return outer;
    }

    private Control BuildPane(EnvPane pane)
    {
        var header = BuildHeader(pane);

        var text = new SelectableTextBlock
        {
            FontFamily = new FontFamily("Cascadia Mono,Consolas,monospace"),
            FontSize = 12,
            TextWrapping = TextWrapping.NoWrap,
            Padding = new Thickness(10, 6),
            Background = Brushes.Transparent
        };
        PopulateInlines(text, pane.Lines);

        var scroll = new ScrollViewer
        {
            HorizontalScrollBarVisibility = Avalonia.Controls.Primitives.ScrollBarVisibility.Auto,
            VerticalScrollBarVisibility   = Avalonia.Controls.Primitives.ScrollBarVisibility.Auto,
            Content = text
        };
        scroll.Bind(ScrollViewer.OffsetProperty, new Binding(nameof(CompareTabViewModel.SharedScrollOffset))
        {
            Source = _vm,
            Mode = BindingMode.TwoWay
        });

        // Line-number gutter pinned to the left of the code, sharing its
        // vertical scroll (see DiffPaneGutter).
        var body = DiffPaneGutter.Wrap(scroll, pane.Lines.Count);

        var outer = new Border
        {
            CornerRadius = new CornerRadius(6),
            BorderBrush = Application.Current!.TryGetResource(
                "ControlStrokeColorDefaultBrush", out var br) ? br as IBrush : Brushes.Gray,
            BorderThickness = new Thickness(1),
            ClipToBounds = true,
            Child = new Grid { RowDefinitions = new RowDefinitions("Auto,*") }
        };
        var grid = (Grid)outer.Child;
        Grid.SetRow(header, 0);
        Grid.SetRow(body, 1);
        grid.Children.Add(header);
        grid.Children.Add(body);
        return outer;
    }

    private Control BuildHeader(EnvPane pane)
    {
        var badge = new Border
        {
            CornerRadius = new CornerRadius(10),
            Padding = new Thickness(10, 3),
            VerticalAlignment = VerticalAlignment.Center,
            Background = (IBrush)ColorStringBrushConverter.Instance.Convert(
                pane.Color, typeof(IBrush), null, System.Globalization.CultureInfo.InvariantCulture)!,
            Child = new TextBlock
            {
                Text = pane.Label,
                Foreground = Brushes.White,
                FontSize = 11,
                FontWeight = FontWeight.SemiBold
            }
        };

        var changedCount = pane.Lines.Count(l => l.State == LineState.Different);
        var metaText = new TextBlock
        {
            Text = changedCount == 0
                ? $"{pane.Lines.Count} lines, in sync"
                : $"{pane.Lines.Count} lines, {changedCount} differ",
            Opacity = 0.55, FontSize = 11,
            VerticalAlignment = VerticalAlignment.Center,
            Margin = new Thickness(10, 0, 0, 0)
        };

        // In the N-way (3+) view, add a base-relative badge so a difference that
        // lives in only one environment is visible at the column level — the
        // per-pane "K differ" text above is N-way-membership based and reads
        // "in sync" on the base even when a sibling differs.
        var meta = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 6, VerticalAlignment = VerticalAlignment.Center };
        meta.Children.Add(metaText);
        var diffBadge = BuildDiffBadge(pane.DiffBadge);
        if (diffBadge is not null) meta.Children.Add(diffBadge);

        // Shared icon-button factory so Copy + Expand/Restore share an
        // identical frame (size, font, padding). Explicit \uXXXX escapes
        // keep the source ASCII-safe so glyphs render reliably regardless
        // of file encoding round-trips.
        static Button MakeIconBtn(string glyph, string tooltip)
        {
            var tb = new TextBlock
            {
                Text                = glyph,
                FontFamily          = new FontFamily("Segoe Fluent Icons,Segoe MDL2 Assets"),
                FontSize            = 13,
                Opacity             = 0.85,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment   = VerticalAlignment.Center,
            };
            var btn = new Button
            {
                Content                    = tb,
                Padding                    = new Thickness(6, 2),
                MinWidth                   = 32,
                MinHeight                  = 26,
                Margin                     = new Thickness(6, 0, 0, 0),
                HorizontalContentAlignment = HorizontalAlignment.Center,
                VerticalContentAlignment   = VerticalAlignment.Center,
            };
            ToolTip.SetTip(btn, tooltip);
            return btn;
        }

        // Copy: Segoe Fluent / MDL2 "Copy" glyph (E8C8).
        var copyBtn = MakeIconBtn("", "Copy");
        copyBtn.Command          = _vm!.CopyAllCommand;
        copyBtn.CommandParameter = pane;

        // Expand / Restore: FullScreen (E740) when collapsed, BackToWindow
        // (E73F) when this pane is already expanded.
        var isExpanded  = _vm.ExpandedPane is not null;
        var expandBtn   = MakeIconBtn(
            isExpanded ? "" : "",
            isExpanded ? "Restore -- show all panes" : "Expand -- show only this pane");
        expandBtn.Command          = isExpanded ? _vm.RestoreCommand : _vm.ExpandCommand;
        expandBtn.CommandParameter = pane;

        /* legacy-block-replaced -- delete-by-comment-out to preserve the
           current Unicode chars in the source-text exactly as they were
           on disk, without risking another encoding round-trip in the
           Edit tool. Compiler ignores comments; runtime never sees this.
        var copyBtn = new Button
        {
            Content = new TextBlock
            {
                Text       = "",
                FontFamily = new FontFamily("Segoe Fluent Icons,Segoe MDL2 Assets"),
                FontSize   = 13,
                Opacity    = 0.85,
            },
            Padding = new Thickness(6, 2),
            MinWidth = 0,
            Margin = new Thickness(6, 0, 0, 0),
            Command = _vm!.CopyAllCommand,
            CommandParameter = pane,
            [ToolTip.TipProperty] = "Copy"
        };
        // Icon-only Expand / Restore -- same chrome convention as Copy:
        //   FullScreen glyph (E740) = "expand this pane"
        //   BackToWindow glyph (E73F) = "restore all panes"
        // Tooltip carries the verb so the affordance stays discoverable.
        var expandBtn = new Button
        {
            Content = new TextBlock
            {
                Text       = _vm.ExpandedPane is null ? "" : "",
                FontFamily = new FontFamily("Segoe Fluent Icons,Segoe MDL2 Assets"),
                FontSize   = 13,
                Opacity    = 0.85,
            },
            Padding = new Thickness(6, 2),
            MinWidth = 0,
            Margin = new Thickness(6, 0, 0, 0),
            Command = _vm.ExpandedPane is null ? _vm.ExpandCommand : _vm.RestoreCommand,
            CommandParameter = pane,
            [ToolTip.TipProperty] = _vm.ExpandedPane is null ? "Expand -- show only this pane" : "Restore -- show all panes"
        };
        */

        var right = new StackPanel
        {
            Orientation = Orientation.Horizontal,
            HorizontalAlignment = HorizontalAlignment.Right
        };
        right.Children.Add(copyBtn);
        right.Children.Add(expandBtn);

        var header = new Grid
        {
            ColumnDefinitions = new ColumnDefinitions("Auto,*,Auto"),
            Background = Application.Current!.TryGetResource(
                "LayerOnAcrylicFillColorDefaultBrush", out var bg) ? bg as IBrush : null,
        };
        Grid.SetColumn(badge, 0);
        Grid.SetColumn(meta,  1);
        Grid.SetColumn(right, 2);
        header.Children.Add(badge);
        header.Children.Add(meta);
        header.Children.Add(right);

        return new Border
        {
            Padding = new Thickness(10, 6),
            Child = header
        };
    }

    private static void PopulateInlines(SelectableTextBlock target, IReadOnlyList<AlignedPaneLine> lines)
    {
        target.Inlines?.Clear();
        if (target.Inlines is null) target.Inlines = new InlineCollection();

        // Theme-aware diff colours so changed lines stay legible in
        // both modes. Falls back to a high-contrast hardcoded pair if
        // the theme tokens haven't loaded yet (e.g. during startup
        // before App.DiffBgBrush has been resolved). Colours match
        // PaneDiffView so the two "compare two objects" surfaces render
        // identically.
        var diffBg = ResolveBrush("App.DiffBgBrush",    new SolidColorBrush(Color.FromArgb(0xFF, 0x7A, 0x5A, 0x00)));
        var diffFg = ResolveBrush("App.DiffFgBrush",    new SolidColorBrush(Color.FromArgb(0xFF, 0xFF, 0xF4, 0xC2)));
        var delBg  = ResolveBrush("App.DiffDelBgBrush", new SolidColorBrush(Color.FromArgb(0xFF, 0x5C, 0x23, 0x33)));
        var delFg  = ResolveBrush("App.DiffDelFgBrush", new SolidColorBrush(Color.FromArgb(0xFF, 0xFF, 0xB3, 0xB3)));
        var addBg  = ResolveBrush("App.DiffAddBgBrush", new SolidColorBrush(Color.FromArgb(0xFF, 0x21, 0x39, 0x2B)));
        var addFg  = ResolveBrush("App.DiffAddFgBrush", new SolidColorBrush(Color.FromArgb(0xFF, 0xB6, 0xF0, 0xB6)));

        for (int i = 0; i < lines.Count; i++)
        {
            var line = lines[i];

            // 2-pane mode: char-level segments from AlignPair → paint only
            // the changed substrings (Removed on the A side, Added on the B
            // side; Equal spans stay plain). This is the git / VS-Code-style
            // highlight the whole engine change is for.
            if (line.Segments is { Count: > 0 } segments)
            {
                foreach (var seg in segments)
                {
                    var (bg, fg) = seg.Kind switch
                    {
                        CharDiff.SegmentKind.Removed => ((IBrush?)delBg, (IBrush?)delFg),
                        CharDiff.SegmentKind.Added   => ((IBrush?)addBg, (IBrush?)addFg),
                        _                            => ((IBrush?)null,  (IBrush?)null),
                    };
                    AddRun(target.Inlines!, seg.Text, bg, fg);
                }
            }
            else
            {
                // N-way (3+ env) fallback: whole-line amber when Different.
                if (line.State == LineState.Different)
                    AddRun(target.Inlines!, line.Text, diffBg, diffFg);
                else
                    AddRun(target.Inlines!, line.Text, null, null);
            }

            if (i < lines.Count - 1) target.Inlines.Add(new LineBreak());
        }
    }

    private static void AddRun(InlineCollection target, string text, IBrush? bg, IBrush? fg)
    {
        // A zero-length run still needs to exist for empty lines so the
        // LineBreak cadence stays aligned across panes.
        var run = new Run(text);
        if (bg is not null) { run.Background = bg; run.FontWeight = FontWeight.SemiBold; }
        if (fg is not null) run.Foreground = fg;
        target.Add(run);
    }

    /// <summary>Per-column diff indicator for the N-way view (mirrors
    /// <see cref="PaneDiffView"/>): "base" on the base column, "in sync" on an
    /// unchanged environment, and a red "≠ N" pill (with a +/−/~ breakdown
    /// tooltip) on any environment that differs from the base.</summary>
    private static Control? BuildDiffBadge(MultiDiffBadge? badge)
    {
        if (badge is null) return null;
        if (badge.IsBase) return MutedChip("base", "The base — every other column is compared against this");
        if (!badge.Differs) return MutedChip("in sync", "Identical to the base");

        var red = ResolveBrush("App.DiffDelGutterBrush", new SolidColorBrush(Color.FromRgb(0xED, 0x1C, 0x24)));
        var chip = new Border
        {
            Background = red, CornerRadius = new CornerRadius(4),
            Padding = new Thickness(6, 1), VerticalAlignment = VerticalAlignment.Center,
            Child = new TextBlock
            {
                Text = $"≠ {badge.Total}", Foreground = Brushes.White,
                FontSize = 10, FontWeight = FontWeight.SemiBold,
            },
        };
        ToolTip.SetTip(chip, $"+{badge.Added} added · −{badge.Removed} removed · ~{badge.Changed} changed (vs base)");
        return chip;
    }

    private static Border MutedChip(string text, string tip)
    {
        var chip = new Border
        {
            Background = Brushes.Transparent,
            BorderBrush = ResolveBrush("App.StrokeBrush", Brushes.Gray),
            BorderThickness = new Thickness(1),
            CornerRadius = new CornerRadius(4),
            Padding = new Thickness(6, 1), VerticalAlignment = VerticalAlignment.Center,
            Child = new TextBlock { Text = text, Opacity = 0.7, FontSize = 10, FontWeight = FontWeight.SemiBold },
        };
        ToolTip.SetTip(chip, tip);
        return chip;
    }

    private static IBrush ResolveBrush(string key, IBrush fallback)
        => Application.Current!.TryGetResource(key, null, out var r) && r is IBrush b ? b : fallback;
}
